docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

version: 2
jobs:
  run-unit-tests:
    <<: *docker-defaults
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Run unit tests
        command: |
          docker-compose run test

  build-and-pack:
    <<: *docker-defaults
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Builds package in Docker container and copies out
        command: |
          mkdir -p ~/app/output
          docker-compose run pack
          docker cp "$(docker ps -q -a -l -f name=pack)":/app/package.tgz ~/app/output
    - store_artifacts:
        path: output
  publish-to-npm:
    docker:
    - image: circleci/node:lts
    steps:
    - checkout
    - run:
        name: Authenticate with NPM
        command: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/app/.npmrc
    - run:
        name: Publish package
        command: |
          yarn publish

workflows:
  version: 2
  test-build-and-pack:
    jobs:
    - run-unit-tests
    - build-and-pack:
        requires:
        - run-unit-tests

  test-and-deploy:
    jobs:
    - run-unit-tests
    - publish-to-npm:
        requires:
          - run-unit-tests
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/